### ISSUE TITLE
【开源自荐】批量为视频生成字幕，同时可翻译字幕为其它语言

### ISSUE THREAD

**Issue by buxuku** [howie6879/weekly#100]
- 项目名称：video-subtitle-master

- 项目地址：https://github.com/buxuku/video-subtitle-master

- 项目简介：无须上传，在本地即可批量为视频生成字幕文件出来，同时也可以通过百度/火山/deeplx翻译 api 将字幕文件翻译成其它语言的字幕文件。学习外文视频再也不愁了👍

- 项目截图 ：

![image](https://github.com/howie6879/weekly/assets/7866330/f06befe5-2d08-4585-b616-6f7d04debe6c)

**Comment by howie6879** [comment]
https://weekly.howie6879.com/2024/06-17~06-23.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC147%E6%9C%9F%EF%BC%89.html
