### ISSUE TITLE
【自荐工具】飞鸟 m3u8 视频下载器-IPTV 播放器

### ISSUE THREAD

**Issue by youwen21** [howie6879/weekly#105]
飞鸟 m3u8 视频下载器是一款 m3u8 下载工具。支持 Windows, MacOS双系统。
包含功能有：
 -  m3u8 和  直播录制 和 点播下载。
 - IPTV 播放 与 自定义源管理。

![flybird-m3u8downloader](https://github.com/youwen21/flybird-m3u8downloader/raw/main/download-preview.png)

![flybird-m3u8downloader-iptv](https://github.com/youwen21/flybird-m3u8downloader/raw/main/iptv-show.jpg)

**Comment by howie6879** [comment]
https://github.com/youwen21/flybird-m3u8downloader

**Comment by howie6879** [comment]
https://weekly.howie6879.com/2024/06-17~06-23.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC147%E6%9C%9F%EF%BC%89.html
