### ISSUE TITLE
可以issue投稿么？

### ISSUE THREAD

**Issue by DiamonWoo** [howie6879/weekly#108]
从周刊的[寄语](https://weekly.howie6879.com/)进来，文末说：

> 如果你有不错的资源希望分享给我，欢迎以[Issue自荐](https://github.com/howie6879/weekly/issues/1)形式和我沟通。

> 最后更新: April 4, 2024

但是点击 [Issue自荐] 显示：This issue has been deleted. 
然后这里空无一文，这是什么情况？还接受投稿吗？

**Comment by DiamonWoo** [comment]
原来以前的issues都close了，那我接着投吧

**Comment by howie6879** [comment]
可以 投稿的，你继续这个 issue 写介绍就行
