### ISSUE TITLE
【自荐工具】多平台自定义源资源聚合工具，支持看小说、漫画、视频等

### ISSUE THREAD

**Issue by aooiuu** [howie6879/weekly#110]
项目地址: https://github.com/aooiuu/any-reader

## 功能亮点

- **跨平台**: Windows、Mac、Linux
- **多应用**: 桌面端、网页端、Docker、VSCode插件、 uTools 插件、rubick 插件
- **多类型**：小说、漫画、视频、~~音频~~
- **自定义源**：通过 XPath、JSONPath、CSS选择器、正则、JS等轻松编写规则
- **生态兼容**：兼容 [eso](https://github.com/mabDc/eso) 源
- **资源站接入**：支持导入苹果CMS、ZyPlayer
- **开放解析库**：规则解析库分离, 你可以使用解析库开发自己的程序
- **本地资源支持**：支持本地小说格式 TXT、Epub

|                                              漫画                                               |                                              小说                                               |                                              视频                                               |
| :---------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------: |
| ![1](https://github.com/aooiuu/any-reader/assets/28108111/7271b8ae-ad9b-41d6-8b2f-bcdf2a814a48) | ![2](https://github.com/aooiuu/any-reader/assets/28108111/7d28d1ad-7b87-40d5-9080-c16f17b78a2e) | ![3](https://github.com/aooiuu/any-reader/assets/28108111/ecd65276-ed1c-4577-b066-d788a322d1f4) |
| ![4](https://github.com/aooiuu/any-reader/assets/28108111/e0a9ec10-e72e-49ed-8610-588f0af17a55) | ![5](https://github.com/aooiuu/any-reader/assets/28108111/997582a4-b69a-4bd9-8cc0-1b661688de4f) | ![6](https://github.com/aooiuu/any-reader/assets/28108111/afebc6dd-16d5-4521-9b9f-72432ad9cb13) |
|                                            聚合搜索                                             |                                            规则列表                                             |                                            规则编辑                                             |
| ![7](https://github.com/aooiuu/any-reader/assets/28108111/aa66ad97-2ce4-4533-b4b5-c4d9c36dccbb) | ![8](https://github.com/aooiuu/any-reader/assets/28108111/11f011e3-af9e-4921-9459-11094e8554c3) | ![9](https://github.com/aooiuu/any-reader/assets/28108111/dc53bb59-9d72-4594-8d3f-2dea5f208998) |

**Comment by howie6879** [comment]
谢谢，已收录 https://weekly.howie6879.com/2024/07-15~07-21.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC151%E6%9C%9F%EF%BC%89.html#any-reader
