### ISSUE TITLE
网站的文章顺序能不能修改一下

### ISSUE THREAD

**Issue by WHYBBE** [howie6879/weekly#12]
我很喜欢你周刊的内容，但我不想使用RSS，也不想使用公众号，只想定期查看一下网页

并且我发现[首页](https://weekly.howie6879.cn/)并不是最新内容，同时[2022导航](https://weekly.howie6879.cn/2022/01-01~01-09.%E6%88%91%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC021%E6%9C%9F%EF%BC%89.html)并不是按最新的文章顺序显示，这导致网页的使用体验并不好

所以，能不能把2022导航页面的文章顺序倒过来，或者在首页顶部添加最新一期的跳转链接

**Comment by howie6879** [comment]
有道理，安排~

**Comment by howie6879** [comment]
@WHYBBE 已解决
