### ISSUE TITLE
【开源自荐】Sink - 基于 Cloudflare 带访问统计的短链系统

### ISSUE THREAD

**Issue by ccbikai** [howie6879/weekly#129]
项目名称：Sink

项目地址：https://github.com/ccbikai/Sink

项目简介：基于 Cloudflare 带访问统计的短链系统

**Comment by howie6879** [comment]
https://weekly.howie6879.com/2024/09-30~10-06.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC162%E6%9C%9F%EF%BC%89.html

已收录
