### ISSUE TITLE
【开源自荐】EagleUse - 把 eagle app 变成我的图片（后台）管理系统

### ISSUE THREAD

**Issue by meetqy** [howie6879/weekly#20]
## 推荐项目

- 项目地址：https://github.com/meetqy/eagleuse 
- 在线体验：https://rao.pics

# 描述

`eagle app`管理图片素材资源，实时生成sqlite db文件 => 生成对应查询API => 创建静态路由 => web显示图片

![](https://github.com/meetqy/eagleuse/raw/dev/readme/flow.webp)

# 截图

![](https://github.com/meetqy/eagleuse/raw/dev/readme/preview.webp)
![](https://github.com/meetqy/eagleuse/blob/dev/readme/1.webp?raw=true)
![](https://github.com/meetqy/eagleuse/raw/dev/readme/6.webp?raw=true)

**Comment by howie6879** [comment]
@meetqy 下一期周刊会加这个项目

**Comment by meetqy** [comment]
> @meetqy 下一期周刊会加这个项目，建议增加 Docker 部署方式

好的，后面我去学习研究下

**Comment by howie6879** [comment]
> > @meetqy 下一期周刊会加这个项目，建议增加 Docker 部署方式
> 
> 好的，后面我去学习研究下

已经添加，见[周刊](https://weekly.howie6879.cn/2023/01-16~01-21.%E6%88%91%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC075%E6%9C%9F%EF%BC%89.html#eagleuse)
