### ISSUE TITLE
【开源自荐】AICodeConvert

### ISSUE THREAD

**Issue by JustAIGithub** [howie6879/weekly#44]
开源的代码转换工具，使用GPT实现；
[AICodeConvert](https://aicodeconvert.com)
主要包含两个功能：
1.自然语言转代码，描述需求就生成对应的代码
2.把代码一键转换为另一种代码语言实现；

**Comment by howie6879** [comment]
已收录 https://weekly.howie6879.com/2023/08-01~08-07.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC102%E6%9C%9F%EF%BC%89.html#aicodeconvert

**Comment by JustAIGithub** [comment]
tks,bro

howie.hu ***@***.***> 于2023年8月18日周五 17:01写道：
