### ISSUE TITLE
【开源自荐】yft-design基于Canvas的开源版"创客贴"

### ISSUE THREAD

**Issue by more-strive** [howie6879/weekly#48]
https://github.com/more-strive/yft-design
使用 Vue3 + TypeScript + Fabric.js + Pinia + Element-Plus，支持 文字、图片、形状、线条、二维码 、条形码几种最常用的元素类型，每一种元素都拥有高度可编辑能力，缩略图显示，模板，支持导出json，svg, image文件。
![index](https://github.com/howie6879/weekly/assets/113762408/f089d027-bd0b-44b1-b650-a05bf2a7f6ce)

**Comment by howie6879** [comment]
忘了回复，抱歉
项目不错，在我的待推荐列表了，希望作者继续迭代，优化交互

**Comment by more-strive** [comment]
谢谢肯定，会继续迭代的

**Comment by howie6879** [comment]
@more-strive 请问你这个项目可以加上docker部署支持吗

**Comment by more-strive** [comment]
可以支持docker，现在是通过打包成dist文件夹，nginx部署的

**Comment by howie6879** [comment]
> 可以支持docker，现在是通过打包成dist文件夹，nginx部署的

可以麻烦支持下吗

**Comment by more-strive** [comment]
可以，晚点更新下

**Comment by howie6879** [comment]
> 可以，晚点更新下

我看还没支持？

https://github.com/dromara/yft-design

**Comment by more-strive** [comment]
近期有点忙，可能要晚几天了

**Comment by more-strive** [comment]
> > 可以，晚点更新下
> 
> 我看还没支持？
> 
> https://githubfast.com/dromara/yft-design

已经更新docker文件内容了，服务器太差了，没办法把整个命令跑起来
`
docker build -f ./docker/Dockerfile . -t yft-design
docker run -d -p 5173:5173 yft-design
`

**Comment by howie6879** [comment]
@more-strive 已推荐

https://weekly.howie6879.com/2024/01-08~01-14.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC124%E6%9C%9F%EF%BC%89.html#yft-design
