### ISSUE TITLE
【建议】是否考虑开启 rss 订阅功能

### ISSUE THREAD

**Issue by i4f2e** [howie6879/weekly#6]
Hi howie,

感谢分享这么好的周刊内容，也关注了公众号接收最新的周刊，我看项目中 之前加入了 mkdocs-rss-plugin的插件好像也做过rss配置，但是最后并没有启用，小小的诉求不知可否考虑下重新配置开启 rss插件 提供 rss 订阅的能力？🙏

**Comment by howie6879** [comment]
用代码重新生成了周刊RSS地址：[https://weekly.howie6879.cn/rss/rss.xml](https://weekly.howie6879.cn/rss/rss.xml)

效果：

<img width="2136" alt="image" src="https://user-images.githubusercontent.com/17047388/171993882-c7b7b59f-c2b7-4315-99d6-9b8b3ace748d.png">

**Comment by eryajf** [comment]
@howie6879 你这个rss客户端用的是什么

**Comment by howie6879** [comment]
@eryajf 你好，使用的是这个开源项目：https://github.com/yang991178/fluent-reader

然后，我发现我们在同一个群啊，千古兄的优质花园，缘分。

**Comment by eryajf** [comment]
> 然后，我发现我们在同一个群啊，千古兄的优质花园，缘分。

哈哈，缘分，我今天一天都徜徉在你的周刊里，学到很多

**Comment by eryajf** [comment]
为啥你的 fluent-reader 是固定的三栏，我下载最新的，貌似无法这样设置

**Comment by howie6879** [comment]
@eryajf 他默认是二栏，你屏幕最大化就应该能弄出来

**Comment by eryajf** [comment]
> 他默认是二栏，你屏幕最大化就应该能弄出来

哈哈，这个真是不知道算bug还是feature，确实拉宽一点出来了
