### ISSUE TITLE
【开源工具推荐】RainbowGPT AI Agent ，免费GPT API 提供 ！！实时接口股票数据分析预测、本地无上限字数知识库搜索问答、Google搜索引擎问答

### ISSUE THREAD

**Issue by ZhuJD-China** [howie6879/weekly#64]
推荐项目
📈RainbowGPT现在包括一个强大的股票分析模块，集成各种技术，提供对股市的全面见解。
⚡RainbowGPT结合了AI Agent代理、GPT-4、GPT3.5、ChatGlm3、Qwen LLM、ChromaDB矢量数据库、Langchain知识库问答检索和谷歌搜索引擎。

项目地址： [RainbowGPT 彩虹GPT](https://github.com/ZhuJD-China/RainbowGPT)

项目描述：
🔄 知识库 QA 搜索最有效的使用是将稀疏检索器（例如 BM25）与密集检索器（例如嵌入相似性）相结合。这种“混合搜索”最佳地利用了两种检索器的互补优势来获取全面的知识。
📊 探索股票分析模块并为您的投资决策解锁宝贵的见解！ 🚀 #StockAnalysis #RainbowGPT #AIInvesting

![exp](https://github.com/howie6879/weekly/assets/50070803/ec198bed-7a32-45a0-9368-4c2462e04d24)
![stock](https://github.com/howie6879/weekly/assets/50070803/b4cfe277-bde6-4863-8bfc-c1150a5f7066)
![Summarization](https://github.com/howie6879/weekly/assets/50070803/d28ea232-2e24-4d00-a278-b572a112d2b4)

**Comment by howie6879** [comment]
我看你这个项目基本没什么更新频率😂

**Comment by ZhuJD-China** [comment]
基本通用性差不多了 大家提需求 接下来给大家做定制的

**Comment by ZhuJD-China** [comment]
前段时间有点事情 搁了一下
