### ISSUE TITLE
【软件自荐】『京墨』开源免费的古诗词文（名句）、歇后语、成语、绕口令、节日等的阅读 APP

### ISSUE THREAD

**Issue by hefengbao** [howie6879/weekly#67]
![1-Pixel](https://github.com/howie6879/weekly/assets/5126901/c42f5a2b-3073-428b-b03b-91332a978e84)

目前的内容有：

1. 古诗词文 10000 首（阙、篇）；

2. 古诗词文名句 10000 句；

3. 歇后语 14026 条；

4. 成语 30895 条；

5. 中国传统色 161 种；

6. 中国传统节日 19 个；

7. 二十四节气；

8. 绕口令 45 段；

9. 知识卡片 464 组；

使用的数据来自网络（主要是 Github 开源的仓库），可在项目仓库查看 README.md 中的说明。

源码仓库：

https://github.com/hefengbao/jingmo

https://gitee.com/hefengbao/jingmo

**Comment by howie6879** [comment]
很好的产品，谢谢自建

前面已经推荐过了哦 

<img width="925" alt="image" src="https://github.com/howie6879/weekly/assets/17047388/40c4188e-755f-4bfb-95a1-0778eb32e360">

**Comment by hefengbao** [comment]
感谢推荐！！！
